/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2023_ed;

/**
 *
 * @author mario
 */
public class Juego_TerminadoPerdido extends javax.swing.JFrame {

    /**
     * Creates new form Juego_TerminadoPerdido
     */
    public Juego_TerminadoPerdido() {
        initComponents();
        setTitle("Car-Factory/¡PERDISTE!");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablaperdida = new javax.swing.JPanel();
        TituloResultadoPerdida = new javax.swing.JLabel();
        ResultadoPerdida = new javax.swing.JLabel();
        TituloSaldoPerdida = new javax.swing.JLabel();
        PresupuestoFinalPerdida = new javax.swing.JLabel();
        TituloOrdenesPerdida = new javax.swing.JLabel();
        txtCantOrdenesPerdida = new javax.swing.JLabel();
        TituloOrdenesRealizadasPerdida = new javax.swing.JLabel();
        txtOrdenesRealizadasPerdida = new javax.swing.JLabel();
        TituloPerdida = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Reintentar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablaperdida.setBackground(new java.awt.Color(35, 31, 32));

        TituloResultadoPerdida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloResultadoPerdida.setForeground(new java.awt.Color(255, 255, 0));
        TituloResultadoPerdida.setText("Resultado: ");
        TituloResultadoPerdida.setToolTipText("");

        ResultadoPerdida.setForeground(new java.awt.Color(204, 0, 0));

        TituloSaldoPerdida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloSaldoPerdida.setForeground(new java.awt.Color(255, 255, 0));
        TituloSaldoPerdida.setText("Saldo Final:  ");
        TituloSaldoPerdida.setToolTipText("");

        PresupuestoFinalPerdida.setForeground(new java.awt.Color(204, 0, 0));

        TituloOrdenesPerdida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloOrdenesPerdida.setForeground(new java.awt.Color(255, 255, 0));
        TituloOrdenesPerdida.setText("Total de ordenes:  ");
        TituloOrdenesPerdida.setToolTipText("");

        txtCantOrdenesPerdida.setForeground(new java.awt.Color(204, 0, 0));

        TituloOrdenesRealizadasPerdida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloOrdenesRealizadasPerdida.setForeground(new java.awt.Color(255, 255, 0));
        TituloOrdenesRealizadasPerdida.setText("Ordenes realizadas:  ");
        TituloOrdenesRealizadasPerdida.setToolTipText("");

        txtOrdenesRealizadasPerdida.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout TablaperdidaLayout = new javax.swing.GroupLayout(Tablaperdida);
        Tablaperdida.setLayout(TablaperdidaLayout);
        TablaperdidaLayout.setHorizontalGroup(
            TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaperdidaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaperdidaLayout.createSequentialGroup()
                        .addComponent(TituloResultadoPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultadoPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaperdidaLayout.createSequentialGroup()
                        .addComponent(TituloSaldoPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PresupuestoFinalPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaperdidaLayout.createSequentialGroup()
                        .addComponent(TituloOrdenesPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantOrdenesPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaperdidaLayout.createSequentialGroup()
                        .addComponent(TituloOrdenesRealizadasPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrdenesRealizadasPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        TablaperdidaLayout.setVerticalGroup(
            TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaperdidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloResultadoPerdida)
                    .addComponent(ResultadoPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloSaldoPerdida)
                    .addComponent(PresupuestoFinalPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloOrdenesPerdida)
                    .addComponent(txtCantOrdenesPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaperdidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloOrdenesRealizadasPerdida)
                    .addComponent(txtOrdenesRealizadasPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(Tablaperdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        TituloPerdida.setBackground(new java.awt.Color(35, 31, 32));
        TituloPerdida.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        TituloPerdida.setForeground(new java.awt.Color(204, 0, 0));
        TituloPerdida.setText("¡PERDISTE!");
        TituloPerdida.setOpaque(true);
        getContentPane().add(TituloPerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 260, 50));

        MenuPrincipal.setBackground(new java.awt.Color(51, 255, 51));
        MenuPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        MenuPrincipal.setText("Menu Principal");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        Reintentar.setBackground(new java.awt.Color(51, 255, 51));
        Reintentar.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        Reintentar.setForeground(new java.awt.Color(0, 0, 0));
        Reintentar.setText("Jugar de nuevo");
        Reintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReintentarActionPerformed(evt);
            }
        });
        getContentPane().add(Reintentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpeg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        // TODO add your handling code here:
        new Ingresar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        new Salir().setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void ReintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReintentarActionPerformed
        new Ordenes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReintentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_TerminadoPerdido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_TerminadoPerdido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_TerminadoPerdido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_TerminadoPerdido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_TerminadoPerdido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton MenuPrincipal;
    public static javax.swing.JLabel PresupuestoFinalPerdida;
    private javax.swing.JButton Reintentar;
    public static javax.swing.JLabel ResultadoPerdida;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel Tablaperdida;
    private javax.swing.JLabel TituloOrdenesPerdida;
    private javax.swing.JLabel TituloOrdenesRealizadasPerdida;
    private javax.swing.JLabel TituloPerdida;
    private javax.swing.JLabel TituloResultadoPerdida;
    private javax.swing.JLabel TituloSaldoPerdida;
    public static javax.swing.JLabel txtCantOrdenesPerdida;
    public static javax.swing.JLabel txtOrdenesRealizadasPerdida;
    // End of variables declaration//GEN-END:variables
}
