/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2023_ed;

/**
 *
 * @author mario
 */
public class Salir extends javax.swing.JFrame {

    /**
     * Creates new form Salir
     */
    public Salir() {
        initComponents();
        setTitle("Car-Factory/Salir");
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JPanel();
        Instrucciones1 = new javax.swing.JLabel();
        bttnCancelar = new javax.swing.JButton();
        bttnSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Instrucciones1.setBackground(new java.awt.Color(35, 31, 32));
        Instrucciones1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Instrucciones1.setForeground(new java.awt.Color(250, 210, 1));
        Instrucciones1.setText("¿Quieres cerrar el programa?");
        Instrucciones1.setOpaque(true);
        Salir.add(Instrucciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 50));

        bttnCancelar.setBackground(new java.awt.Color(10, 180, 110));
        bttnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        bttnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });
        Salir.add(bttnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        bttnSalir.setBackground(new java.awt.Color(230, 50, 20));
        bttnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        bttnSalir.setForeground(new java.awt.Color(255, 255, 255));
        bttnSalir.setText("Salir");
        bttnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSalirActionPerformed(evt);
            }
        });
        Salir.add(bttnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpeg"))); // NOI18N
        Salir.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 130));

        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bttnCancelarActionPerformed

    private void bttnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Instrucciones1;
    private javax.swing.JPanel Salir;
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JButton bttnSalir;
    // End of variables declaration//GEN-END:variables
}
